version: '3'
services:
  redis:
      container_name: egame-redis
      image: egame-redis
      build:
        context: ..
        dockerfile: build/DockerfileRedis
      volumes:
        - .\conf\redis\redis.conf:/usr/local/etc/redis/redis.conf
      ports:
        - "6380:6379"
      command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
      restart: on-failure:5
  mysql:
    container_name: egame-mysql
    image: mysql:5.7
    environment:
      # MYSQL_ALLOW_EMPTY_PASSWORD: "yes"  # 允许空密码
      MYSQL_ROOT_PASSWORD: mindy123
      MYSQL_DATABASE: egame
      MYSQL_USER: egame
      MYSQL_PASSWORD: mindy123
    ports:
      - "3310:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:


  # web:
  #   container_name: egame-web
  #   image: egame-web
  #   build:
  #     context: ..
  #     dockerfile: build/DockerfileWeb
  #   volumes:
  #      - ..\:/home/egame
  #   ports:
  #     - 20010:20010
  #   depends_on:
  #     - mysql
  #     - redis
  #   links:
  #     - mysql:localmysql
  #     - redis:localredis
