// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
//文件生產器

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "gphper",
            "url": "https://eGame-demo-back-office-api"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/example/index": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "示例"
                ],
                "summary": "展示用户信息",
                "operationId": "1",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "年龄",
                        "name": "age",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "性别",
                        "name": "sex",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "username",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.UserReq"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/api.DefaultResponse"
                        }
                    }
                }
            }
        },
        "/user/refresh": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "刷新jtoken",
                "operationId": "4",
                "parameters": [
                    {
                        "type": "string",
                        "name": "retoken",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":1,\"msg\":\"success\",\"data\":{\"jtoken\":\"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFeHAiOiIyMDIxLTEyLTI2VDE5OjI1OjI4Ljg0OTIzNzUrMDg6MDAiLCJOYW1lIjoiZ3BocGVyIiwiVWlkIjo0fQ==.ab81bb7134978afe976df55b45789aefd10f6c3edb969bae283c32c080083b89\"}}",
                        "schema": {
                            "type": "json"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/api.DefaultResponse"
                        }
                    }
                }
            }
        },
        "/user/login": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "用户登录",
                "operationId": "3",
                "parameters": [
                    {
                        "type": "string",
                        "name": "email",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.UserLoginRes"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/api.DefaultResponse"
                        }
                    }
                }
            }
        },
        "/user/register": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "用户注册",
                "operationId": "2",
                "parameters": [
                    {
                        "type": "string",
                        "name": "confirm_password",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "email",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "nickname",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/api.DefaultResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.DefaultResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "code 为1表示正常 0表示业务请求错误",
                    "type": "integer"
                },
                "msg": {
                    "description": "错误提示信息",
                    "type": "string"
                }
            }
        },
        "api.SuccessResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "code 为1表示正常 0表示业务请求错误",
                    "type": "integer"
                },
                "data": {
                    "description": "接口返回的业务数据",
                    "type": "object"
                },
                "msg": {
                    "description": "错误提示信息",
                    "type": "string"
                }
            }
        },
        "models.UserLoginRes": {
            "type": "object",
            "properties": {
                "jtoken": {
                    "description": "Jtoken 验证字符串",
                    "type": "string"
                },
                "retoken": {
                    "description": "retoken 刷新token",
                    "type": "string"
                }
            }
        },
        "models.UserReq": {
            "type": "object",
            "required": [
                "age",
                "sex",
                "username"
            ],
            "properties": {
                "age": {
                    "description": "年龄",
                    "type": "integer"
                },
                "sex": {
                    "description": "性别",
                    "type": "integer"
                },
                "username": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        }
    }
}`




// SwaggerInfo holds exported Swagger Info so clients can modify it
type swaggerInfo struct {
	Version     string        // 版本號
	Host        string        // 主機名稱和端口
	BasePath    string        // 基礎路徑
	Schemes     []string      // 協議方案，例如 HTTP 或 HTTPS
	Title       string        // Swagger 文檔的標題
	Description string        // Swagger 文檔的描述
}

// SwaggerInfo 保存了 Swagger 的信息，允许客户端进行修改

var SwaggerInfo = swaggerInfo{
	Version:     "1.0",                        // 版本號
	Host:        "localhost:20011",            // 主機名稱和端口
	BasePath:    "/api",                       // 基礎路徑
	Schemes:     []string{},                   // 協議方案，此處為空列表
	Title:       "Egame Api",                  // Swagger 文檔的標題
	Description: "Egame 後台",                 // Swagger 文檔的描述
}

type s struct{} // 定義一個空結構體 s


// ReadDoc 讀取並返回 Swagger 文檔
func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{}) // 在 Swagger 中註冊結構體 s
}
